name: nz_actions_bus
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  rxdart: ^0.28.0
  nz_common: ^1.0.0
  meta: ^1.16.0

dev_dependencies:
  nz_lint: ^1.0.0
