name: nz_boxes
description: "A new Flutter package project."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  nz_common:
    path: ../nz_common
  shared_preferences: ^2.3.2
  logging: ^1.3.0

dev_dependencies:
  nz_lint: ^1.0.0

