name: nz_drift
description: "A new Flutter package project."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  drift: ^2.19.1+1
  nz_common: ^1.0.0
  nz_base_models: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.19.1
  nz_lint: ^1.0.0
  test: ^1.26.2
