list:
  title: 'Settings'
  blocks:
    lookAndFeel: 'Look and feel'
    storage: 'Storage'
    other: 'Other'

theme:
  title: 'Theme'
  useDynamicColorsOption:
    title: 'Use dynamic colors'
    subtitle: App's theme would adapt on system accent colors
  harmonizeColors:
    title: 'Harmonized colors'
    subtitle: 'All the custom colors would be more integrated into app theme'
  values:
    light: 'Light theme'
    dark: 'Dark theme'
    system: 'Prefer system theme'

specialEffects:
  title: 'Special effects'

storage:
  title: 'Backup data'
  aboutHeader: 'How it works'
  aboutContent: |
    You can export all of your app data into single JSON file and then import at any time on any device.
    ⚠️ Warning: while app is in early stage of development, data and formats between versions can be changed and then data can be lost.
  importTitle: 'Import'
  exportTitle: 'Export'
  fileDialog:
    saveTitle: 'Choose where to store backup file...'
  importStatus:
    process: 'Importing your data...'
    successTitle: 'Restart required'
    success: |
      You successfully imported app's data!
      For finishing this process, please restart this app
    failure: |
      Something went wrong. Your data wasn't imported :(
      Try again on some other file
  exportStatus:
    process: 'Exporting your data...'
    success: 'You successfully exported your data!'
    failure: |
      Something went wrong. Your data wasn't exported ;(
      Try to restart an app
  closeAppButton: 'Close this app!'

debug:
  title: Debug settings
  blocks:
    language: 'App language'

about:
  title: 'About'
  blocks:
    version: 'App version'
    links: 'Links'
    telegram: 'Telegram'
    repository: 'Source code'
    licenses: 'Licenses'
