name: not_zero_app
description: Task management and well-being app.
publish_to: 'none'
version: 0.14.0+24
resolution: workspace

environment:
  sdk: '^3.10.0'

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  form_builder_validators: ^11.0.0
  go_router: ^17.0.0
  intl: ^0.20.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  nz_actions_bus: ^1.0.0
  nz_base_models: ^1.0.0
  nz_boxes: ^1.0.0
  nz_common: ^1.0.0
  nz_drift: ^1.0.0
  nz_flutter_core: ^1.0.0
  nz_logger: ^1.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  flutter_riverpod: ^3.0.0
  drift: ^2.20.0
  drift_flutter: ^0.2.7
  dynamic_color: ^1.8.1
  collection: ^1.19.1
  flutter_confetti: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  nz_lint: ^1.0.0
  alchemist: ^0.13.0

flutter:
  default-flavor: dev
  fonts:
    - family: NotZero
      fonts:
        - asset: assets/fonts/NotZero.ttf
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont.ttf

  uses-material-design: true
