name: nz_base_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  freezed_annotation: ^3.1.0
  nz_common: ^1.0.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^3.2.3
  nz_lint: ^1.0.0
  test: ^1.26.3
