list:
  title: "Настройки"
  blocks:
    lookAndFeel: "Внешний вид"
    storage: "Хранилище"
    other: "Другое"

theme:
  title: "Тема"
  useDynamicColorsOption:
    title: "Использовать динамические цвета"
    subtitle: "Тема приложения будет подстраиваться под системный акцентный цвет"
  harmonizeColors:
    title: "Гармонизация цветов"
    subtitle: "Пользовательские цвета будут лучше сочетаться с темой приложения"
  values:
    light: "Светлая тема"
    dark: "Тёмная тема"
    system: "Как в системе"

specialEffects:
  title: "Спецэффекты"

storage:
  title: "Резервное копирование данных (в разработке)"
  aboutHeader: "Как это работает"
  aboutContent: |
    Вы можете экспортировать все данные приложения в один JSON-файл и затем импортировать его в любой момент на любом устройстве.
    ⚠️ Внимание: пока приложение на ранней стадии разработки, форматы данных могут меняться между версиями — из-за этого данные могут быть потеряны.
  importTitle: "Импорт"
  exportTitle: "Экспорт"
  importStatus:
    process: "Импорт данных..."
    successTitle: "Требуется перезапуск"
    success: |
      Вы успешно импортировали данные приложения!
      Чтобы завершить процесс, перезапустите приложение
    failure: |
      Что-то пошло не так. Данные не были импортированы :(
      Попробуйте выбрать другой файл
  exportStatus:
    process: "Экспорт данных..."
    success: "Вы успешно экспортировали данные!"
    failure: |
      Что-то пошло не так. Данные не были экспортированы ;(
      Попробуйте перезапустить приложение
  closeAppButton: "Закрыть приложение!"

debug:
  title: Для разработчиков
  blocks:
    language: 'Язык приложения'

about:
  title: "О приложении"
  blocks:
    version: "Версия приложения"
    links: "Ссылки"
    telegram: "Telegram"
    repository: "Исходный код"
    licenses: "Лицензии"
